"""remove telefone column (UserTable)

Revision ID: 0184295ed89c
Revises: 67e03a94d08b
Create Date: 2026-04-15 22:57:00.022797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0184295ed89c'
down_revision: Union[str, Sequence[str], None] = '67e03a94d08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'telefone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
