"""added new status column to UserTable, remove ativo column and remove ExcludedUserTable

Revision ID: 044cc4bb2b5b
Revises: cda9437d7b96
Create Date: 2026-05-03 20:38:04.930588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '044cc4bb2b5b'
down_revision: Union[str, Sequence[str], None] = 'cda9437d7b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_excluidos')
    op.add_column('usuarios', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', sa.BOOLEAN(), nullable=True))
    op.drop_column('usuarios', 'status')
    op.create_table('usuarios_excluidos',
    sa.Column('id_utilizado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('excluido_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_utilizado', name=op.f('usuarios_excluidos_pkey'))
    )
    # ### end Alembic commands ###
