"""add email verification columns (user)

Revision ID: 3d48baf9213f
Revises: 54434251d8cb
Create Date: 2026-05-14 17:16:56.141289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d48baf9213f'
down_revision: Union[str, Sequence[str], None] = '54434251d8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email_verificado', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('email_verification_expira_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'email_verification_expira_em')
    op.drop_column('usuarios', 'email_verification_token')
    op.drop_column('usuarios', 'email_verificado')
    # ### end Alembic commands ###
