"""remove usuario_id foreignkey

Revision ID: 5336d1ec0e57
Revises: 8ecf1a7104b6
Create Date: 2026-04-20 19:21:39.047824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5336d1ec0e57'
down_revision: Union[str, Sequence[str], None] = '8ecf1a7104b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pedidos_usuario_id_fkey'), 'pedidos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('pedidos_usuario_id_fkey'), 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
