"""add email tokens

Revision ID: 54434251d8cb
Revises: f337de15bcaa
Create Date: 2026-05-11 18:40:27.642938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54434251d8cb'
down_revision: Union[str, Sequence[str], None] = 'f337de15bcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_expira_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'reset_token_expira_em')
    op.drop_column('usuarios', 'reset_token')
    # ### end Alembic commands ###
