"""adiciona precos por tamanho

Revision ID: f337de15bcaa
Revises: 044cc4bb2b5b
Create Date: 2026-05-09 17:09:46.965753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f337de15bcaa'
down_revision: Union[str, Sequence[str], None] = '044cc4bb2b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardapio', sa.Column('preco_pequeno', sa.Float(), nullable=False))
    op.add_column('cardapio', sa.Column('preco_tradicional', sa.Float(), nullable=False))
    op.add_column('cardapio', sa.Column('preco_grande', sa.Float(), nullable=False))
    op.drop_column('cardapio', 'preco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardapio', sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('cardapio', 'preco_grande')
    op.drop_column('cardapio', 'preco_tradicional')
    op.drop_column('cardapio', 'preco_pequeno')
    # ### end Alembic commands ###
